stages:
  - build

build-hickory-dns-tests:
  stage: build
  image: rust:latest
  tags:
    - docker
  variables:
    CARGO_HOME: ${CI_PROJECT_DIR}/.cargo
  cache:
    key: hickory-dns-tests-musl
    paths:
      - .cargo/
      - hickory-dns-tests/target/
  before_script:
    - rustup target add x86_64-unknown-linux-musl
    - apt-get update -qq && apt-get install -y -qq musl-tools
  script:
    - cd hickory-dns-tests
    - cargo build --release --target x86_64-unknown-linux-musl
  artifacts:
    name: "hickory-dns-tests-${CI_COMMIT_SHORT_SHA}"
    paths:
      - hickory-dns-tests/target/x86_64-unknown-linux-musl/release/hickory-dns-tests
    expire_in: 4 weeks
